### ISSUE TITLE
Uncaught ReferenceError: actions is not defined

### ISSUE THREAD

**Issue by lmartins** [joehoyle/atom-autocomplete-wordpress-hooks#1]
[Enter steps to reproduce below:]
1. While creating new `add_action` declarations this happens everytime

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package, v0.1.1
### Stack Trace

Uncaught ReferenceError: actions is not defined

```
At /Users/luismartins/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:95

ReferenceError: actions is not defined
    at /Users/luismartins/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:95:12
    at Array.filter (native)
    at Object.module.exports.getHook (/Users/luismartins/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:94:29)
    at Object.module.exports.getSuggestions (/Users/luismartins/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:66:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
 11x -1:20.8.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:19.7.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:19.7.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:18 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -1:11.9.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:08.1.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  9x -1:07.7.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:04.9.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:04.9.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:04.7.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:04.7.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.9.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:07.6.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:07.6.0 snippets:expand (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:05.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -0:04.6.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "autocomplete",
      "autohide-tree-view",
      "powerline",
      "language-objective-c",
      "archive-view",
      "language-clojure",
      "language-c",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "welcome",
      "layout-manager",
      "file-type-icons",
      "wrap-guide",
      "smalls",
      "linter-jshint",
      "symbols-tree-view"
    ],
    "projectHome": "/Users/luismartins/Sites",
    "ignoredNames": [
      ".DS_Store",
      "bower_components",
      "node_modules",
      "build",
      "jspm_packages"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-dark-fusion-syntax, v0.7.0
atomatigit, v1.5.4
autocomplete-paths, v1.0.2
autocomplete-wordpress-hooks, v0.1.1
color-picker, v2.0.13
css-snippets, v0.9.0
cursor-history, v0.5.5
docblockr, v0.7.3
expand-region, v0.2.3
feedback, v0.38.0
file-icons, v1.6.11
javascript-snippets, v1.0.0
language-diff, v0.3.1
linter, v1.8.1
linter-php, v1.0.5
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-selection, v4.3.1
nucleus-dark-ui, v0.6.3
php-debug, v0.1.3
php-twig, v4.0.0
relative-numbers, v0.2.4
remember-file-positions, v0.1.6
term3, v0.19.0
vim-mode, v0.61.0
vim-surround, v0.8.0
wordpress-api, v1.2.1
wordpress-dictionary, v4.3.7

# Dev
No dev packages
```

**Comment by joehoyle** [comment]
Fixed in v0.2.0
