### ISSUE TITLE
Uncaught TypeError: Cannot read property '3' of undefined

### ISSUE THREAD

**Issue by CarlosRGL** [joehoyle/atom-autocomplete-wordpress-hooks#10]
when typing a WP function like get_site_url in lastest beta (1.19 beta1)

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '3' of undefined

```
At /Users/CarlicosRGL/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '3' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -3:09.0 core:save (input.hidden-input)
     -2:48 emmet:expand-abbreviation (input.hidden-input)
     -2:47.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -2:44.5.0 autocomplete-plus:confirm (input.hidden-input)
     -2:44.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:44.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:44.1.0 editor:newline (input.hidden-input)
     -0:28.9.0 emmet:expand-abbreviation (input.hidden-input)
     -0:26.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:19.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:19.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:backspace (input.hidden-input)
     -0:13.8.0 snippets:next-tab-stop (input.hidden-input)
  2x -0:12.8.0 core:move-left (input.hidden-input)
     -0:12.4.0 snippets:next-tab-stop (input.hidden-input)
     -0:12.4.0 snippets:expand (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.2 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-wrap-in-tag 0.6.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.66.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-php 1.3.2 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
multi-cursor 2.1.5 
oceanic-next 1.0.0 
pigments 0.39.1 
project-manager 3.3.5 
sync-settings 0.8.2 
tab-foldername-index 2.0.3 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
tree-view-autoresize 2.1.0 
tree-view-copy-relative-path 1.2.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
