### ISSUE TITLE
Uncaught TypeError: Cannot read property '13' of undefined

### ISSUE THREAD

**Issue by ebadia** [joehoyle/atom-autocomplete-wordpress-hooks#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '13' of undefined

```
At /Users/ebadia/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '13' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
  5x -0:20 core:move-down (input.hidden-input)
  3x -0:06.5.0 core:move-up (input.hidden-input)
  4x -0:06.0 core:move-left (input.hidden-input)
     -0:04.7.0 core:move-right (input.hidden-input)
     -0:02.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angular2-snippets 0.4.0 
angularjs 0.4.0 
atom-easy-jsdoc 4.12.1 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-typescript 11.0.6 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
autocomplete-wordpress-hooks 0.2.2 
block-comment 0.4.3 
busy-signal 1.4.3 
emmet 2.4.3 
font-awesome-snippetset 0.0.6 
intentions 1.1.2 
language-babel 2.66.1 
language-vue 0.23.0 
language-vue-component 0.5.0 
linter 2.2.0 
linter-jscs 4.1.2 
linter-ui-default 1.6.2 
meteor-api 2.20.0 
nativescript-ng2-atom-snippets 1.2.0 
open-in-browser 0.5.2 
p5js-snippets 0.3.1 
p5xjs-autocomplete 2.3.0 
pinegrow-atom 0.3.1 
platformio-ide-terminal 2.5.3 
project-manager 3.3.5 
react-redux-snippets 0.1.6 
react-snippets 0.8.0 
Remote-FTP 1.1.2 
seti-icons 1.5.4 
Sublime-Style-Column-Selection 1.7.4 
tree-ignore 0.6.2 
vim-mode-plus 0.93.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
