### ISSUE TITLE
Uncaught TypeError: Cannot read property '17' of undefined

### ISSUE THREAD

**Issue by Droidism-zz** [joehoyle/atom-autocomplete-wordpress-hooks#14]
[Enter steps to reproduce:]

1. Open Atom -> open files or project
2. Edit one file and then just sit and watch this error appear

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '17' of undefined

```
At /Users/xxxx/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '17' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:56 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:26.1.0 core:copy (input.hidden-input)
     -1:25.5.0 project-find:show (input.hidden-input)
     -0:51 core:backspace (input.hidden-input)
  2x -0:39.8.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -0:03.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap3 1.2.12 
atom-minify 0.8.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
css-comb 2.5.0 
editorconfig 2.2.2 
file-icons 2.1.10 
goto-definition 1.3.4 
highlight-line 0.12.0 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 1.3.4 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-ui-default 1.6.3 
minimap 4.29.3 
pigments 0.40.1 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
