### ISSUE TITLE
Uncaught TypeError: Cannot read property '19' of undefined

### ISSUE THREAD

**Issue by phh** [joehoyle/atom-autocomplete-wordpress-hooks#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '19' of undefined

```
At C:\Users\Patrick\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '19' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -0:19.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:19.4.0 docblockr:parse-enter (input.hidden-input)
     -0:19.4.0 editor:newline (input.hidden-input)
     -0:19.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:19.2.0 docblockr:parse-enter (input.hidden-input)
     -0:19.2.0 editor:newline (input.hidden-input)
  3x -0:17.3.0 core:move-left (input.hidden-input)
     -0:09.6.0 core:backspace (input.hidden-input)
     -0:08.6.0 core:move-right (input.hidden-input)
     -0:08.0 intentions:highlight (input.hidden-input)
     -0:07.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-alignment 0.13.0 
atom-beautify 0.30.4 
atom-wordpress 0.3.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.10 
git-blame 1.2.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.2.0 
linter-js-yaml 1.2.7 
linter-php 1.3.2 
linter-ui-default 1.6.3 
merge-conflicts 1.4.5 
open-recent 5.0.0 
pigments 0.40.1 
project-manager 3.3.5 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sync-settings 0.8.2 
tabs-to-spaces 1.0.3 
todo-show 1.11.0 
trailing-spaces 0.4.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
