### ISSUE TITLE
Uncaught TypeError: Cannot read property '75' of undefined

### ISSUE THREAD

**Issue by laposlaszlo** [joehoyle/atom-autocomplete-wordpress-hooks#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '75' of undefined

```
At /Users/laszlolapos/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '75' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -2:02.8.0 editor:newline (input.hidden-input)
     -2:01.8.0 core:backspace (input.hidden-input)
     -2:00.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:00.3.0 snippets:expand (atom-text-editor.editor.is-focused)
  3x -1:57.8.0 core:save (input.hidden-input)
  2x -1:19.7.0 core:backspace (input.hidden-input)
     -1:18.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:18.4.0 core:save (input.hidden-input)
     -0:50.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:50.8.0 editor:newline (input.hidden-input)
     -0:45.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:45.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:43.9.0 intentions:highlight (input.hidden-input)
     -0:42.3.0 core:backspace (input.hidden-input)
  2x -0:42 intentions:highlight (input.hidden-input)
 10x -0:05.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.4 
atom-wordpress 0.3.0 
auto-detect-indentation 1.3.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
dash 1.7.1 
Delete-Whitelines 0.6.3 
emmet 2.4.3 
expose 0.14.0 
html-entities 0.4.0 
intentions 1.1.5 
jonikorpi-atom-theme-ui 4.4.1 
language-haml 0.25.0 
language-twig 1.6.3 
language-vue 0.23.1 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.3 
native-ui 0.21.0 
php-twig 4.0.0 
pigments 0.40.1 
project-manager 3.3.5 
rails-snippets 2.16.0 
remote-edit 1.9.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.10.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wp-dev 0.3.5 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
