### ISSUE TITLE
Uncaught TypeError: Cannot read property '132' of undefined

### ISSUE THREAD

**Issue by ikaiser** [joehoyle/atom-autocomplete-wordpress-hooks#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '132' of undefined

```
At /Users/macbookpro15/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '132' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -4:42.7.0 find-and-replace:show (input.hidden-input)
     -4:42.6.0 core:paste (input.hidden-input)
     -4:42.4.0 core:confirm (input.hidden-input)
  2x -4:41.2.0 core:backspace (input.hidden-input)
     -4:40.6.0 core:confirm (input.hidden-input)
     -0:53.9.0 core:close (input.hidden-input)
     -0:17.1.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:16.7.0 core:copy (input.hidden-input)
     -0:16.6.0 core:move-right (input.hidden-input)
     -0:16.4.0 editor:newline (input.hidden-input)
     -0:16.2.0 core:paste (input.hidden-input)
     -0:15.7.0 editor:move-to-first-character-of-line (input.hidden-input)
 15x -0:15.4.0 core:select-right (input.hidden-input)
     -0:09.1.0 autocomplete-plus:cancel (input.hidden-input)
  4x -0:05.7.0 core:move-right (input.hidden-input)
     -0:03.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-css-comb 3.3.1 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
autocomplete-modules 1.6.10 
autocomplete-php 0.3.7 
autocomplete-ruby 0.2.8 
autocomplete-swift 1.0.3 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
codeigniter 0.3.2 
cordova-de-debugger 2.1.0 
cordova-snippets 0.1.0 
cucumber 0.6.0 
cucumber-step 0.2.0 
file-icons 2.1.10 
git-history 3.3.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
goto-definition 1.3.4 
hyperclick 0.1.3 
intentions 1.1.5 
java-generator 2.2.3 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-docker 1.1.8 
language-gettext 0.6.1 
language-leaf 0.1.1 
language-rspec 0.6.3 
language-swift 0.5.0 
language-vue 0.23.1 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-javac 1.9.4 
linter-php 1.3.2 
linter-rubocop 2.1.1 
linter-ruby 1.2.5 
linter-scss-lint 3.1.0 
linter-swiftc 2.0.0 
linter-ui-default 1.6.3 
linter-write-good 0.9.0 
monokai-seti 0.9.0 
monokai-soft 0.2.0 
nord-atom-ui 0.11.0 
phonegap-snippets 0.1.0 
platformio-ide-terminal 2.5.5 
qolor 0.4.2 
rails-i18n-autocomplete 0.4.0 
rails-snippets 2.16.0 
Remote-FTP 1.1.3 
rubocop-auto-correct 1.5.1 
ruby-test 1.0.2 
script 3.15.0 
seti-ui 1.9.0 
swift-debugger 0.1.2 
sync-settings 0.8.2 
tabs-to-spaces 1.0.3 
todo-show 1.11.0 
vue2-autocomplete 0.1.0-alpha.4 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
