### ISSUE TITLE
Uncaught TypeError: Cannot read property '63' of undefined

### ISSUE THREAD

**Issue by backlands** [joehoyle/atom-autocomplete-wordpress-hooks#18]
[Enter steps to reproduce:]

1. Open a PHP file.
2. Start typing a WordPress hook.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '63' of undefined

```
At /Users/erick/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '63' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -3:23.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
  4x -3:20.9.0 core:move-down (input.hidden-input)
     -3:20 core:confirm (input.hidden-input)
     -3:20 project-manager:save-project (div.tool-panel.tree-view)
     -3:11.6.0 core:focus-next (input.input-text)
     -3:10.6.0 core:select-all (input.input-text)
     -3:04.0 project-manager:list-projects (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
  9x -3:02.9.0 core:move-down (input.hidden-input)
  4x -3:01.5.0 core:move-up (input.hidden-input)
     -3:00.7.0 core:move-down (input.hidden-input)
     -2:59.6.0 core:confirm (input.hidden-input)
  2x -0:50.1.0 core:copy (input.hidden-input)
     -0:42 core:paste (input.hidden-input)
  2x -0:38.1.0 editor:newline (input.hidden-input)
     -0:10.8.0 spaces-in-braces:run-backspace-check (input.hidden-input)
     -0:10.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-radiant-player 1.0.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
dash-ui 0.4.2 
file-icons 2.1.10 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.69.0 
less-autocompile 1.0.0 
linter 2.2.0 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-pigments 0.2.2 
monokai 0.24.0 
open-recent 5.0.0 
pigments 0.40.1 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
react 0.16.2 
sass-autocompile 0.13.3 
spaces-in-braces 0.1.0 
sync-settings 0.8.2 
trailing-spaces 0.4.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
