### ISSUE TITLE
Uncaught TypeError: Cannot read property '15' of undefined

### ISSUE THREAD

**Issue by CYBORGAO** [joehoyle/atom-autocomplete-wordpress-hooks#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '15' of undefined

```
At C:\Users\cyborg\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '15' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -7:58.1.0 core:move-left (input.hidden-input)
 12x -7:57.4.0 core:backspace (input.hidden-input)
     -6:11.2.0 command-palette:toggle (input.hidden-input)
 22x -6:02.2.0 core:backspace (input.hidden-input)
     -5:48.1.0 editor:consolidate-selections (input.hidden-input)
     -5:48.1.0 core:cancel (input.hidden-input)
  7x -4:31 core:backspace (input.hidden-input)
     -4:27.4.0 autocomplete-plus:confirm (input.hidden-input)
  6x -4:26.4.0 core:backspace (input.hidden-input)
     -4:23.3.0 core:move-down (input.hidden-input)
     -4:16.9.0 core:move-right (input.hidden-input)
  2x -4:16.5.0 core:move-left (input.hidden-input)
  5x -4:15 core:backspace (input.hidden-input)
     -2:38.3.0 spell-check:toggle (input.hidden-input)
  2x -1:39.8.0 core:confirm (input.hidden-input)
     -0:14 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-wordpress-hooks 0.2.2 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
