### ISSUE TITLE
Uncaught TypeError: Cannot read property '232' of undefined

### ISSUE THREAD

**Issue by kingkool68** [joehoyle/atom-autocomplete-wordpress-hooks#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '232' of undefined

```
At /Users/rheimlich/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '232' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
 11x -2:25.8.0 core:close (input.hidden-input)
     -1:45.7.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:41.2.0 project-find:show (input.hidden-input)
  2x -1:38.5.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  2x -1:20 core:close (input.hidden-input)
     -1:18.1.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:16.2.0 core:confirm (input.hidden-input)
     -0:13.6.0 docblockr:parse-enter (input.hidden-input)
     -0:13.6.0 editor:newline (input.hidden-input)
  2x -0:08.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
auto-update-packages 1.0.1 
autocomplete-paths 1.0.5 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
docblockr 0.11.0 
editorconfig undefined 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-jshint 3.1.5 
linter-phpcs 1.6.7 
linter-stylelint 4.0.1 
linter-ui-default 1.6.4 
multi-cursor 2.1.5 
php-twig 4.0.0 
phpcbf 0.2.1 
pigments 0.40.1 
pretty-json 1.6.4 
project-manager 3.3.5 
seti-icons 1.5.4 
sort-lines 0.14.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
