### ISSUE TITLE
Uncaught TypeError: Cannot read property '113' of undefined

### ISSUE THREAD

**Issue by saumya010** [joehoyle/atom-autocomplete-wordpress-hooks#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Single Language
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '113' of undefined

```
At C:\Users\Admin\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '113' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
  6x -1:01.6.0 core:move-right (input.hidden-input)
  6x -0:51.9.0 core:move-left (input.hidden-input)
     -0:50.5.0 editor:select-to-end-of-word (input.hidden-input)
     -0:49.7.0 core:backspace (input.hidden-input)
     -0:45.7.0 core:save (input.hidden-input)
     -0:43.3.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:43 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:40.4.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:40 pane:move-active-item-to-top-of-stack (input.hidden-input)
  3x -0:28.7.0 core:move-left (input.hidden-input)
     -0:27.8.0 core:backspace (input.hidden-input)
     -0:14.6.0 core:move-down (input.hidden-input)
     -0:14.2.0 core:move-left (input.hidden-input)
  3x -0:05.1.0 core:move-up (input.hidden-input)
     -0:03.1.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:02.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-wordpress-hooks 0.2.2 
codebug 1.0.0 
file-type-icons 1.3.4 
highlight-selected 0.13.1 
Remote-FTP 1.1.3 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
