### ISSUE TITLE
Uncaught TypeError: Cannot read property '10' of undefined

### ISSUE THREAD

**Issue by ru55ell** [joehoyle/atom-autocomplete-wordpress-hooks#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '10' of undefined

```
At /Users/russelltaylor/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '10' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -8:18.9.0 core:save (input.hidden-input)
     -6:11.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
  4x -6:03.9.0 core:backspace (input.hidden-input)
     -5:55.4.0 core:confirm (input.hidden-input)
     -5:41.4.0 editor:newline (input.hidden-input)
     -5:37 core:copy (input.hidden-input)
     -5:34.6.0 core:select-all (input.hidden-input)
     -5:34.4.0 core:paste (input.hidden-input)
     -5:27.8.0 core:backspace (input.hidden-input)
     -5:23 editor:newline (input.hidden-input)
  8x -5:17.2.0 core:backspace (input.hidden-input)
     -4:38.9.0 core:save (input.hidden-input)
  4x -3:54.9.0 core:backspace (input.hidden-input)
     -3:34.3.0 github:toggle-git-tab (input.hidden-input)
     -2:27 core:paste (input.hidden-input)
  2x -0:07.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
platformio-ide-terminal 2.5.5 
Remote-FTP 1.1.3 
seti-ui 1.9.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
