### ISSUE TITLE
Uncaught TypeError: Cannot read property '346' of undefined

### ISSUE THREAD

**Issue by lallen30** [joehoyle/atom-autocomplete-wordpress-hooks#24]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '346' of undefined

```
At C:\Users\Larry\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '346' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -0:42.1.0 core:move-right (input.hidden-input)
     -0:41.4.0 autoclose-html:close-and-complete (input.hidden-input)
  3x -0:40.7.0 core:select-right (input.hidden-input)
     -0:40.1.0 core:backspace (input.hidden-input)
     -0:38.6.0 core:delete (input.hidden-input)
  8x -0:38.1.0 core:move-right (input.hidden-input)
 14x -0:34.6.0 core:move-left (input.hidden-input)
     -0:32.9.0 intentions:highlight (input.hidden-input)
     -0:32.8.0 core:paste (input.hidden-input)
 11x -0:32.1.0 core:move-left (input.hidden-input)
 30x -0:28.9.0 core:select-left (input.hidden-input)
  4x -0:23.8.0 core:backspace (input.hidden-input)
     -0:19.8.0 autoclose-html:close-and-complete (input.hidden-input)
  2x -0:19.2.0 core:backspace (input.hidden-input)
     -0:18.5.0 autoclose-html:close-and-complete (input.hidden-input)
  3x -0:17.9.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.1.1 
atom-autocomplete-php 0.25.6 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
codeigniter 0.3.2 
color-picker 2.2.5 
file-icons 2.1.10 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
jscs-fixer 1.3.0 
less-than-slash 0.17.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-phpmd 1.5.3 
linter-scss-lint 3.1.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
project-manager 3.3.5 
simple-drag-drop-text 0.3.4 
sync-settings 0.8.2 
todo-show 1.11.0 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
