### ISSUE TITLE
Uncaught TypeError: Cannot read property '28' of undefined

### ISSUE THREAD

**Issue by jonnale** [joehoyle/atom-autocomplete-wordpress-hooks#25]
Steps to reproduce:

1. Edit some text
2. Press ctrl+z to undo.
-  Error popped up.

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '28' of undefined

```
At C:\Users\J2\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '28' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -7:00.9.0 core:backspace (input.hidden-input)
     -7:00.2.0 core:move-right (input.hidden-input)
  2x -6:59.9.0 core:backspace (input.hidden-input)
  2x -6:59.1.0 core:delete (input.hidden-input)
     -6:58.7.0 intentions:highlight (input.hidden-input)
     -6:58.2.0 core:save (input.hidden-input)
     -6:44.4.0 intentions:highlight (input.hidden-input)
  3x -6:44.3.0 core:undo (input.hidden-input)
     -6:42.7.0 core:save (input.hidden-input)
     -6:33.4.0 intentions:highlight (input.hidden-input)
  2x -6:33.2.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -6:32.6.0 core:backspace (input.hidden-input)
     -6:32.3.0 intentions:highlight (input.hidden-input)
  2x -6:31.3.0 core:delete (input.hidden-input)
     -6:31 intentions:highlight (input.hidden-input)
     -6:30.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-sublime-monokai-syntax 0.4.4 
atom-wordpress 0.3.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
git-plus 7.9.3 
hyperclick 0.1.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.4 
metro-syntax 0.3.1 
metro-ui 2.2.2 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base undefined 
php-integrator-call-tips 1.2.1 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter 1.3.0 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips 1.1.5 
php-integrator-tooltips-legacy-php56 1.1.6 
project-manager 3.3.5 
Remote-FTP 1.1.3 
spotify-ui 1.2.2 
Sublime-Style-Column-Selection 1.7.4 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
