### ISSUE TITLE
Uncaught TypeError: Cannot read property '261' of undefined

### ISSUE THREAD

**Issue by shakeeb-mts** [joehoyle/atom-autocomplete-wordpress-hooks#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '261' of undefined

```
At C:\Users\shak\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '261' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -8:54.8.0 intentions:highlight (input.hidden-input)
     -8:54.6.0 core:paste (input.hidden-input)
     -8:53.1.0 core:save (input.hidden-input)
     -8:47.2.0 core:backspace (input.hidden-input)
     -8:47.1.0 intentions:highlight (input.hidden-input)
  3x -8:47 editor:delete-to-beginning-of-word (input.hidden-input)
     -8:45.9.0 core:undo (input.hidden-input)
     -8:45.2.0 core:paste (input.hidden-input)
     -8:44.9.0 core:save (input.hidden-input)
     -8:39.2.0 core:move-down (input.hidden-input)
     -8:39 intentions:highlight (input.hidden-input)
  4x -8:38.9.0 editor:move-to-beginning-of-word (input.hidden-input)
  8x -8:37.5.0 editor:select-to-end-of-word (input.hidden-input)
     -8:35.8.0 core:select-right (input.hidden-input)
     -8:35.4.0 core:paste (input.hidden-input)
     -8:34.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.2 
autoprefixer 3.7.1 
busy-signal 1.4.3 
csscomb 0.3.1 
docblockr 0.11.0 
goto-definition 1.3.4 
grunt-runner 0.14.0 
highlight-selected 0.13.1 
html-to-css 0.2.2 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-ui-default 1.6.4 
livereload 0.4.4 
minimap 4.29.6 
project-manager 3.3.5 
sass-autocompile 0.13.3 
tabs-to-spaces 1.0.3 
todo-show 1.11.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
