### ISSUE TITLE
Uncaught TypeError: Cannot read property '27' of undefined

### ISSUE THREAD

**Issue by yaser-alazm** [joehoyle/atom-autocomplete-wordpress-hooks#28]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '27' of undefined

```
At C:\Users\Mr.Robot\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '27' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -3:31 core:select-all (input.hidden-input)
     -3:15.3.0 core:confirm (input.hidden-input)
     -0:58.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:58.3.0 editor:newline (input.hidden-input)
     -0:58.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:58.2.0 editor:newline (input.hidden-input)
  7x -0:25.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-bootstrap3 1.2.12 
atom-ternjs 0.18.3 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
intentions 1.1.5 
javascript-snippets 1.2.1 
jslint 1.5.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
open-in-browsers 0.0.30 
php-integrator-base 3.0.1 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
script 3.15.0 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
