### ISSUE TITLE
Uncaught TypeError: Cannot read property '11' of undefined

### ISSUE THREAD

**Issue by yuriy-vasilyev** [joehoyle/atom-autocomplete-wordpress-hooks#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '11' of undefined

```
At /Users/yuriyvasilyev/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '11' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:17.4.0 core:paste (input.hidden-input)
 17x -1:16.3.0 core:move-left (input.hidden-input)
  9x -1:15 core:select-left (input.hidden-input)
     -1:11.7.0 find-and-replace:select-next (input.hidden-input)
     -0:29.8.0 core:backspace (input.hidden-input)
     -0:22 core:select-right (input.hidden-input)
     -0:21.8.0 core:backspace (input.hidden-input)
 21x -0:21.5.0 core:move-right (input.hidden-input)
     -0:16.9.0 core:copy (input.hidden-input)
     -0:11 core:paste (input.hidden-input)
     -0:09.7.0 core:move-right (input.hidden-input)
     -0:09.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:09.1.0 editor:newline (input.hidden-input)
     -0:08.2.0 core:move-up (input.hidden-input)
     -0:07.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -0:07.5.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
close-on-left 0.8.0 
docker 0.7.0 
emmet 2.4.3 
es6-javascript 1.0.0 
react-es6-snippets 0.3.0 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-snippets 0.9.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
