### ISSUE TITLE
Uncaught TypeError: Cannot read property '49' of undefined

### ISSUE THREAD

**Issue by iFediai** [joehoyle/atom-autocomplete-wordpress-hooks#30]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '49' of undefined

```
At C:\Users\Eugen\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '49' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -0:15.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -0:06.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap4 1.4.0 
atom-material-syntax 1.0.6 
autocomplete-paths 1.0.5 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
chester-atom-syntax 0.2.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
highlight-selected 0.13.1 
html-to-css 0.2.2 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-ui-default 1.6.4 
merge-conflicts 1.4.5 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
