### ISSUE TITLE
Uncaught TypeError: Cannot read property '9' of undefined

### ISSUE THREAD

**Issue by dodancs** [joehoyle/atom-autocomplete-wordpress-hooks#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '9' of undefined

```
At C:\Users\Dominik\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '9' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -5:40.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -4:00.4.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -0:17.9.0 editor:newline (input.hidden-input)
     -0:12.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
android 0.1.0 
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-java 1.2.7 
autocomplete-json 5.5.0 
autocomplete-wordpress-hooks 0.2.2 
chester-atom-syntax 0.2.1 
color-picker 2.2.5 
file-header 1.13.4 
file-icons 2.1.10 
git-control 0.9.0 
increment-me 0.4.1 
language-lua 0.9.11 
minimap 4.29.6 
pigments 0.40.2 
Remote-FTP 1.1.3 
wakatime 7.0.3 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
