### ISSUE TITLE
Uncaught TypeError: Cannot read property '32' of undefined

### ISSUE THREAD

**Issue by wilnarvaez** [joehoyle/atom-autocomplete-wordpress-hooks#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '32' of undefined

```
At C:\Users\wilme\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '32' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -6:28.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.8.1 
autocomplete-wordpress-hooks 0.2.2 
autoprefixer 3.7.1 
color-picker 2.2.5 
emmet 2.4.3 
highlight-selected 0.13.1 
livereload 0.4.4 
pigments 0.39.1 
webbox-color 0.5.9 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
