### ISSUE TITLE
Uncaught TypeError: Cannot read property '86' of undefined

### ISSUE THREAD

**Issue by PatrikundIsabeller** [joehoyle/atom-autocomplete-wordpress-hooks#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: PATRIK
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '86' of undefined

```
At C:\Users\Patrik\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '86' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -4:36.5.0 application:open-folder (atom-pane.pane.active)
     -3:46.9.0 github:toggle-git-tab (input.hidden-input)
  2x -3:20.3.0 core:backspace (input.hidden-input)
     -3:03.9.0 github:toggle-github-tab (div.github-Panel.is-empty)
     -1:59 settings-view:install-packages-and-themes (input.hidden-input)
     -1:51.9.0 core:confirm (input.hidden-input)
  3x -0:29.3.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-wordpress-hooks 0.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
