### ISSUE TITLE
Uncaught TypeError: Cannot read property '271' of undefined

### ISSUE THREAD

**Issue by ajithrn** [joehoyle/atom-autocomplete-wordpress-hooks#34]
[Enter steps to reproduce:]

1. Error appear when try to edit the code, by adding space

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: elementary OS
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '271' of undefined

```
At /home/user/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '271' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:09.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
aligner-scss 1.3.1 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
autocomplete-paths 2.5.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
autoupdate-packages 1.3.1 
blade-snippets 0.2.0 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
comment-headers 2.15.0 
css-snippets 1.1.0 
custom-title 1.0.1 
docblockr 0.11.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.10 
gist 1.0.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.34.0 
linter 2.2.0 
linter-phpcs 1.6.7 
linter-ui-default 1.6.4 
local-history 4.3.0 
merge-conflicts 1.4.5 
minimap 4.29.6 
php-cs-fixer 4.1.0 
php-debug 0.2.5 
pigments 0.40.2 
project-manager 3.3.5 
project-plus 1.0.0 
sync-settings 0.8.2 
tag 0.5.0 
terminal-plus 0.14.5 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
