### ISSUE TITLE
Uncaught TypeError: Cannot read property '8' of undefined

### ISSUE THREAD

**Issue by raymacz** [joehoyle/atom-autocomplete-wordpress-hooks#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2
**User**: root

### Stack Trace

Uncaught TypeError: Cannot read property '8' of undefined

```
At /home/raymacz/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '8' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:28 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-css-comb 3.3.1 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-ui-default 1.6.4 
minimap 4.29.6 
open-recent 5.0.0 
pigments 0.40.2 
Remote-FTP 1.1.3 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
