### ISSUE TITLE
Uncaught TypeError: Cannot read property '7' of undefined

### ISSUE THREAD

**Issue by osamaabdalla** [joehoyle/atom-autocomplete-wordpress-hooks#36]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '7' of undefined

```
At /Users/USER/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '7' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:32.4.0 editor:outdent-selected-rows (input.hidden-input)
     -1:32.1.0 snippets:previous-tab-stop (input.hidden-input)
     -1:32.1.0 editor:outdent-selected-rows (input.hidden-input)
     -1:30.6.0 core:copy (input.hidden-input)
     -1:30 core:paste (input.hidden-input)
     -1:17.9.0 core:copy (input.hidden-input)
     -1:16.3.0 core:paste (input.hidden-input)
     -1:15.7.0 snippets:previous-tab-stop (input.hidden-input)
     -1:15.7.0 editor:outdent-selected-rows (input.hidden-input)
     -1:12.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:12.8.0 editor:newline (input.hidden-input)
  6x -1:07.0 core:backspace (input.hidden-input)
     -1:05.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:05.7.0 editor:newline (input.hidden-input)
  4x -1:02.6.0 core:backspace (input.hidden-input)
     -0:45.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.4 
atom-typescript 11.0.6 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
bade3-notepad-syntax 0.3.4 
busy-signal 1.4.3 
color-picker 2.2.5 
Delete-Whitelines 0.6.3 
emmet 2.4.3 
google-translate-modal 1.2.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.3 
nuclide 0.243.0 
react 0.16.2 
skeuomorphic-notepad-theme 0.2.8 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
