### ISSUE TITLE
Uncaught TypeError: Cannot read property '23' of undefined

### ISSUE THREAD

**Issue by aurovrata** [joehoyle/atom-autocomplete-wordpress-hooks#37]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '23' of undefined

```
At /Users/aurovrata/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '23' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Dev/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Dev/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Dev/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -7:54.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -3:03.9.0 core:copy (input.hidden-input)
     -3:03.7.0 core:paste (input.hidden-input)
     -2:09.4.0 core:copy (input.hidden-input)
     -1:28.1.0 core:paste (input.hidden-input)
     -1:20 core:move-right (input.hidden-input)
  6x -1:19.6.0 core:backspace (input.hidden-input)
     -1:02.0 core:save (input.hidden-input)
     -0:27.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
aligner-php 1.1.1 
atom-beautify 0.30.5 
atom-ctags 5.1.0 
atom-debugger 0.1.6 
atom-gdb 0.6.0 
atom-prettify 0.1.3 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
codebug 1.0.0 
color-picker 2.2.5 
file-icons 2.1.10 
goto-definition 1.3.4 
highlight-line 0.12.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.5 
php-cs-fixer 4.1.0 
php-debug 0.2.5 
pigments undefined 
project-manager 3.3.5 
spacegray-atom-dark-syntax 1.3.2 
split-diff 1.4.3 
tidy-tabs 0.4.0 
wordpress-api 1.2.2 
wp-debug-watcher 1.3.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
