### ISSUE TITLE
Uncaught TypeError: Cannot read property '24' of undefined

### ISSUE THREAD

**Issue by vhld522** [joehoyle/atom-autocomplete-wordpress-hooks#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '24' of undefined

```
At /Users/victorhugoleondelgado/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '24' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -7:00.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -0:12.6.0 core:move-down (input.hidden-input)
     -0:12.4.0 core:move-left (input.hidden-input)
  2x -0:12.1.0 core:move-up (input.hidden-input)
  2x -0:11.7.0 core:move-right (input.hidden-input)
     -0:11.2.0 core:move-down (input.hidden-input)
     -0:11 core:move-right (input.hidden-input)
     -0:10.8.0 core:move-up (input.hidden-input)
     -0:10.4.0 core:move-right (input.hidden-input)
     -0:10.2.0 core:move-down (input.hidden-input)
     -0:09.9.0 core:move-right (input.hidden-input)
  2x -0:09.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.10 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
