### ISSUE TITLE
Uncaught TypeError: Cannot read property '4' of undefined

### ISSUE THREAD

**Issue by nibushibu** [joehoyle/atom-autocomplete-wordpress-hooks#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '4' of undefined

```
At /Users/nibushibu/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '4' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:37.6.0 tree-view:reveal-active-file (input.hidden-input)
     -1:26.9.0 project-manager:list-projects (div.tool-panel.tree-view)
     -1:25.8.0 core:confirm (input.hidden-input)
     -1:18 tree-view:add-file (span.name.icon.icon-file-directory)
 12x -1:11.4.0 core:move-left (input.hidden-input)
     -1:06.9.0 core:confirm (input.hidden-input)
     -0:53.8.0 core:paste (input.hidden-input)
     -0:17.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:17.1.0 docblockr:parse-enter (input.hidden-input)
  6x -0:10 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ascii-codes 0.3.3 
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-dark-ui-slim 0.47.1 
atom-fix-path 0.1.0 
atom-html-preview 0.1.22 
atom-light-ui-slim 0.25.1 
atomic-chrome 0.3.2 
auto-encoding 0.7.0 
autocomplete-paths 2.8.0 
autocomplete-wordpress-hooks 0.2.2 
autoprefixer 3.7.1 
bezier-curve-editor 0.7.2 
busy-signal 1.4.3 
calc 0.4.0 
clipboard-plus 0.5.1 
color-picker 2.2.5 
cursor-history 0.12.0 
docblockr 0.11.0 
double-tag 0.9.0 
duotone-dark-syntax 2.1.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.11 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
git-time-machine 1.5.9 
grammar-token-limit 0.1.1 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-entities 0.4.0 
intentions 1.1.5 
japan-util 0.2.0 
japanese-zen-han-convert 0.5.0 
json-converter 0.2.4 
language-actionscript 0.2.0 
language-ejs 0.4.0 
language-postcss 1.3.1 
language-pug 0.0.21 
last-tab 0.1.6 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.7 
local-history 4.3.0 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-autohider 1.5.3 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
monokai 0.24.0 
pigments 0.40.2 
project-manager 3.3.5 
regex-railroad-diagram 0.19.3 
riot-tag 1.1.1 
set-syntax 0.3.2 
show-ideographic-space 1.0.2 
sort-lines 0.14.0 
space-tab 0.4.2 
split-diff 1.4.4 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.2 
tag 0.5.0 
todo 0.6.0 
todo-show 1.11.0 
toggle-quotes 1.0.1 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
