### ISSUE TITLE
Uncaught TypeError: Cannot read property '536' of undefined

### ISSUE THREAD

**Issue by LucaPipolo** [joehoyle/atom-autocomplete-wordpress-hooks#40]
# Steps to reproduce the issue

1. Open a Wordpress PHP file;
2. Save the file;

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

# Stack Trace

Uncaught TypeError: Cannot read property '536' of undefined

```
At /Users/lucapipolo/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '536' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

# Commands

```
     -1:00.6.0 window:toggle-full-screen (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-syntax.theme-atom-material-ui)
     -0:53.1.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-syntax.theme-atom-material-ui)
     -0:48.7.0 tabs:close-all-tabs (div.title.icon.php-icon.dark-blue)
     -0:42.1.0 project-find:show (div.tool-panel.tree-view)
     -0:42 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-syntax.theme-atom-material-ui.find-visible)
     -0:41.7.0 core:paste (input.hidden-input)
     -0:40.9.0 core:select-all (input.hidden-input)
     -0:40.6.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:40.1.0 core:paste (input.hidden-input)
     -0:36.4.0 core:confirm (input.hidden-input)
     -0:33.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:31.1.0 core:confirm (input.hidden-input)
     -0:19.4.0 editor:newline (input.hidden-input)
     -0:17.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:17.2.0 snippets:expand (input.hidden-input)
     -0:13.3.0 core:save (input.hidden-input)
```

# Non-Core Packages

```
aligner-php 1.1.1 
atom-csscomb 3.0.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
auto-update-packages 1.0.1 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
color-picker 2.2.5 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
file-icons 2.1.11 
highlight-selected 0.13.1 
intentions 1.1.5 
language-pug 0.0.21 
linter 2.2.0 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-phpmd 1.5.3 
linter-scss-lint 3.1.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.7 
merge-conflicts 1.4.5 
minimap 4.29.6 
project-manager 3.3.5 
sync-settings 0.8.2 
tabs-to-spaces 1.0.3 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
