### ISSUE TITLE
Uncaught TypeError: Cannot read property '54' of undefined

### ISSUE THREAD

**Issue by MarceloBFreitas** [joehoyle/atom-autocomplete-wordpress-hooks#41]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '54' of undefined

```
At C:\Users\MARCELO\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '54' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -9:48.4.0 core:save (input.hidden-input)
     -3:42.2.0 core:copy (input.hidden-input)
  2x -1:32.7.0 core:backspace (input.hidden-input)
  7x -0:57.6.0 core:undo (input.hidden-input)
     -0:53.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.8 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
gruvbox 1.0.7 
laravel-forms-bootstrap-snippets 1.2.0 
minimap 4.29.6 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
wp-dev 0.3.5 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
