### ISSUE TITLE
Uncaught TypeError: Cannot read property '58' of undefined

### ISSUE THREAD

**Issue by aa2f** [joehoyle/atom-autocomplete-wordpress-hooks#42]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '58' of undefined

```
At C:\Users\atifia\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '58' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -4:01.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:01.0 editor:newline (input.hidden-input)
  3x -3:44 core:backspace (input.hidden-input)
     -3:42.2.0 core:save (input.hidden-input)
  4x -3:26.3.0 core:backspace (input.hidden-input)
     -3:22.6.0 core:confirm (input.hidden-input)
     -2:40.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:39.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:39.6.0 snippets:expand (input.hidden-input)
     -2:39.6.0 editor:indent (input.hidden-input)
  6x -2:38.9.0 core:backspace (input.hidden-input)
     -2:36 snippets:next-tab-stop (input.hidden-input)
     -2:36 snippets:expand (input.hidden-input)
     -2:36 editor:indent (input.hidden-input)
  6x -2:35.3.0 core:backspace (input.hidden-input)
     -2:29.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
autocomplete-wordpress-hooks 0.2.2 
emmet 2.4.3 
highlight-selected 0.13.1 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
