### ISSUE TITLE
Uncaught TypeError: Cannot read property '33' of undefined

### ISSUE THREAD

**Issue by matteous1** [joehoyle/atom-autocomplete-wordpress-hooks#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '33' of undefined

```
At C:\Users\matte\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '33' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at C:/ProgramData/matte/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (C:/ProgramData/matte/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (C:/ProgramData/matte/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
  2x -3:24.3.0 editor:newline (input.hidden-input)
     -0:21.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
