### ISSUE TITLE
Uncaught TypeError: Cannot read property '25' of undefined

### ISSUE THREAD

**Issue by mawk-khan** [joehoyle/atom-autocomplete-wordpress-hooks#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '25' of undefined

```
At C:\Users\Wajid Khan\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '25' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -3:31.6.0 core:paste (input.hidden-input)
     -3:26.9.0 core:select-all (input.hidden-input)
     -3:26.5.0 core:paste (input.hidden-input)
     -3:22.9.0 core:copy (span.syntax--meta.syntax--string-contents.syntax--quoted.syntax--single.syntax--php)
     -3:21.3.0 core:paste (input.hidden-input)
  2x -3:19.8.0 find-and-replace:show (input.hidden-input)
     -2:54.2.0 core:save (input.hidden-input)
     -2:29.2.0 core:copy (input.hidden-input)
     -2:26.7.0 core:paste (input.hidden-input)
     -2:18.6.0 core:delete (input.hidden-input)
     -2:13.8.0 core:save (button.btn.btn-next.disabled)
 57x -2:10.7.0 core:page-up (input.hidden-input)
 19x -1:40 core:undo (input.hidden-input)
  7x -1:37.8.0 core:redo (input.hidden-input)
     -1:32.5.0 core:delete (input.hidden-input)
     -0:16.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autoclose-html 0.23.0 
autocomplete-wordpress-hooks 0.2.2 
emmet 2.4.3 
file-icons 2.1.11 
linter 2.2.0 
linter-csslint 1.3.4 
linter-phpcs 1.6.7 
minimap-highlight-selected 4.6.1 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
