### ISSUE TITLE
Uncaught TypeError: Cannot read property '79' of undefined

### ISSUE THREAD

**Issue by ghost** [joehoyle/atom-autocomplete-wordpress-hooks#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '79' of undefined

```
At /Users/sfs/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '79' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
  2x -1:18.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-live-server 2.1.2 
atom-wordpress 0.3.0 
autocomplete-php 0.3.7 
autocomplete-wordpress-hooks 0.2.2 
emmet 2.4.3 
file-icons 2.1.11 
minimap 4.29.6 
terminal-plus 0.14.5 
wordpress-autocomplete 1.2.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
