### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by fabiodesouza** [joehoyle/atom-autocomplete-wordpress-hooks#47]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\Fabio\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '0' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:10.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:07.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.7 
autocomplete-corona 1.0.7 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
docblockr 0.11.0 
emmet 2.4.3 
git-plus 7.9.3 
intentions 1.1.5 
language-lua 0.9.11 
linter 2.2.0 
linter-ui-default 1.6.7 
minimap 4.29.6 
pigments 0.40.2 
wordpress-api 1.2.2 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
