### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by sushil50889** [joehoyle/atom-autocomplete-wordpress-hooks#48]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At C:\Users\USER007\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '1' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -0:22.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
angularjs 0.4.0 
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
atom-node-debugger 2.1.2 
atom-nodejs-snippets 2.0.0 
atom-terminal 0.8.0 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
autocomplete-json 5.5.0 
autocomplete-modules 1.6.10 
autocomplete-wordpress-hooks 0.2.2 
best-js-snippets 4.1.0 
busy-signal 1.4.3 
cdn-libs 0.1.2 
csslint 1.1.5 
emmet 2.4.3 
es6-javascript 1.0.0 
expressjs 2.2.0 
file-icons 2.1.11 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-mongodb 0.3.1 
linter 2.2.0 
linter-ui-default 1.6.7 
minimap 4.29.6 
node-debug 0.1.7 
node-debugger 1.10.1 
node-on-fire 0.1.0 
node-require 1.0.0 
node-requirer 0.1.12 
node-snippets 0.0.7 
nodejs-snippets 2.0.2 
nodemon-atom 0.1.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
Quick-JavaScript 2.2.0 
require-anywhere 2.0.7 
standardjs-snippets 2.6.0 
todo 0.6.0 
tree-view-git-status 1.4.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
