### ISSUE TITLE
Uncaught TypeError: Cannot read property '82' of undefined

### ISSUE THREAD

**Issue by sachinnawale99** [joehoyle/atom-autocomplete-wordpress-hooks#50]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '82' of undefined

```
At C:\Users\Sorted Pixel\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '82' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
 18x -9:56.6.0 core:backspace (input.hidden-input)
  5x -9:12 core:move-down (input.hidden-input)
     -9:10.2.0 autocomplete-plus:confirm (input.hidden-input)
     -9:10.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -9:07.2.0 core:undo (input.hidden-input)
 17x -9:05.9.0 core:backspace (input.hidden-input)
     -2:06.0 core:undo (input.hidden-input)
 11x -2:05.2.0 core:backspace (input.hidden-input)
  3x -1:22.1.0 core:move-down (input.hidden-input)
     -1:20.3.0 core:move-up (input.hidden-input)
     -1:19.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:15.9.0 core:move-left (input.hidden-input)
  3x -1:11.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.13 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
Hydrogen 1.20.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
