### ISSUE TITLE
Uncaught TypeError: Cannot read property '228' of undefined

### ISSUE THREAD

**Issue by pstonier** [joehoyle/atom-autocomplete-wordpress-hooks#51]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '228' of undefined

```
At /Users/paulstonier/.atom/packages/autocomplete-wordpress-hooks/lib/provider.js:111

TypeError: Cannot read property '228' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -3:05.1.0 find-and-replace:show (input.hidden-input)
  2x -3:03.3.0 core:backspace (input.hidden-input)
     -3:01.8.0 core:confirm (input.hidden-input)
  2x -2:03.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-html-preview 0.1.22 
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
autocomplete-modules 1.6.10 
autocomplete-wordpress-hooks 0.2.2 
color-picker 2.2.5 
color-tabs 0.1.8 
debug-service 0.0.1 
docker 0.7.0 
dracula-syntax 2.0.5 
emmet 2.4.3 
file-icons 2.1.11 
indent-guide-improved 1.4.13 
ionic-preview 0.7.0 
language-svg 0.9.2 
lint 0.0.1 
php-server 0.7.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
seti-ui-beta 0.1.1 
split-diff 1.5.0 
svg-preview 0.11.0 
w3c-validation 0.4.0 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 1.1.1 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3

**Comment by pstonier** [comment]
Thanks, Joe!

**Comment by burhandodhy** [comment]
Much needed update. Thanks 👍
