### ISSUE TITLE
Uncaught TypeError: Cannot read property '11' of undefined

### ISSUE THREAD

**Issue by WackiDesign** [joehoyle/atom-autocomplete-wordpress-hooks#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-wordpress-hooks](https://github.com/joehoyle/atom-autocomplete-wordpress-hooks) package 0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '11' of undefined

```
At C:\Users\info\.atom\packages\autocomplete-wordpress-hooks\lib\provider.js:111

TypeError: Cannot read property '11' of undefined
    at Object.isInFilter (/packages/autocomplete-wordpress-hooks/lib/provider.js:111:41)
    at Object.getSuggestions (/packages/autocomplete-wordpress-hooks/lib/provider.js:37:13)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -1:02.4.0 core:delete (input.hidden-input)
     -0:58.7.0 intentions:highlight (input.hidden-input)
     -0:58.5.0 core:copy (input.hidden-input)
  3x -0:58.1.0 core:delete (input.hidden-input)
     -0:49.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:49.1.0 editor:newline (input.hidden-input)
     -0:48.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:48.9.0 editor:newline (input.hidden-input)
     -0:48.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:48.4.0 intentions:highlight (input.hidden-input)
     -0:48.1.0 core:paste (input.hidden-input)
 46x -0:34.9.0 intentions:highlight (input.hidden-input)
  3x -0:30.7.0 core:delete (input.hidden-input)
     -0:25.9.0 editor:consolidate-selections (input.hidden-input)
     -0:08.6.0 core:delete (input.hidden-input)
     -0:06.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-html-preview 0.1.22 
atom-terminal 0.8.0 
atom-typescript 11.0.3 
atom-wordpress 0.3.0 
autocomplete-wordpress-hooks 0.2.2 
busy-signal 1.4.3 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.7 
git-plus 7.9.3 
grunt-runner 0.14.0 
html-id-class-snippets 1.4.1 
intentions 1.1.2 
jslint 1.5.1 
language-latte 0.3.5 
less-autocompile 1.0.0 
linter 2.1.4 
linter-ui-default 1.6.1 
minimap 4.28.2 
pigments 0.39.1 
Remote-FTP 0.10.7 
simple-drag-drop-text 0.3.4 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
svgo 2.8.5 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
```

**Comment by joehoyle** [comment]
Fixed in v0.2.3
